apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        -
          image: mongo
          name: mongodb
          ports:
            -
              containerPort: 27017
              name: mongodb
          volumeMounts:
            -
              mountPath: /mongo/data/db
              name: mongodb-persistent-storage
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-persistent-storage
