apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-storage
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
